version: '3.8'
services:
  app:
    container_name: app-tempo-challenge
    image: davidortizalbornoz/tempo-challenge:1.0.0
    networks:
      - tempo-challenge-red
    ports:
      - "8080:8080"
    depends_on:
      - postgres_container_local
      - redis_container_local

  pgadmin_container_local:
    container_name: pgadmin_container_local
    image: dpage/pgadmin4:7.8
    networks:
      - tempo-challenge-red
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: name@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      PYTHONPATH: /pgadmin4

  redis_container_local:
    container_name: redis_container_local
    image: redis:7.2.7-alpine3.21
    networks:
      - tempo-challenge-red
    ports:
      - "6379:6379"
    command:
      redis-server --bind 0.0.0.0 --protected-mode no

  postgres_container_local:
    container_name: postgres_container_local
    image: postgres:16-alpine3.20
    networks:
      - tempo-challenge-red
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./docker-postgres-init:/docker-entrypoint-initdb.d
      - postgres_data_2:/var/lib/postgresql/data

volumes:
  postgres_data_2:
    name: postgres_data_2

networks:
  tempo-challenge-red:
    name: tempo-challenge-red
    driver: bridge
